server:
  port: 8012

spring:
  datasource:
    url: jdbc:log4jdbc:oracle:thin:@localhost:1521:xe
    # db_log
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: Semi
    password: semi
  servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB